print("       __") 
print("     _ ||")
print("    / \||")
print("   /   \|")
print("  /     \ ")
print("  |     |")
print("  |     |")
print(" ---------")


print("             (o)===============(o)")
print("             //                 \\ ")
print("            //                   \\")
print("        ___//_                    \\")
print("       /      \                    \\  ")
print("      /        \                    \\  ")
print("     /          \                    \\  ")
print("    /            \                    \\  ")
print("    --------------                     \\")
print("                                        \\")
print("                                        (o)")
print("                                        //")
print("                                       //")
print("                                      //")
print("                                     //")
print("                                    //")
print("                                   //")
print("                                  //")
print("                                 //")
print("                                //")
print("                   ||          //")
print("              ==========================")
